### ISSUE TITLE
时钟表盘

### ISSUE THREAD

**Issue by tvrcgo** [tvrcgo/paper#5]
一个时钟表盘，秒钟一秒一动。

效果
![qq 20150522161240](https://cloud.githubusercontent.com/assets/237062/7766669/35029b52-009e-11e5-8d0f-e3f732ea207d.png)

HTML 结构很简单，一个表盘，三个指针
```html
<div class="clock-board">
	<div class="hour"></div>
	<div class="minute"></div>
	<div class="second"></div>
</div>
```

CSS
```css
.clock-board {
	background: #ddd; border-radius: 50%; display: inline-block; width: 200px; height: 200px; position: relative;
}
.second, .minute, .hour {
	position: absolute; display: inline-block; width: 95px;	top: 99px; left: 100px;	border: 1px solid red; border-width: 1px 0; transform-origin: 0 50%;
}
.minute {
	width: 80px; top: 98px; border-color: #333; border-width: 2px 0;
}
.hour {
	width: 50px; top: 96px; border-color: #333; border-width: 4px 0;
}
.ease {
	transition: all 0.5s ease;
}
```

JavaScript
```js
$(function(){

	var reset = true;

	setInterval(function(){
		var time = new Date();
		var hour = time.getHours();
		var minute = time.getMinutes();
		var second = time.getSeconds();

		var hour_deg = (hour + minute/60)*30 - 90;
		var minute_deg = (minute + second/60)*6 - 90;
		var second_pre = Math.floor(Date.now()/(1000*3600*24))*360;
		var second_deg = second_pre + second*6 - 90;

		$('.hour').css('transform', "rotate("+hour_deg+"deg)");
		$('.minute').css('transform', "rotate("+minute_deg+"deg)");
		$('.second').css('transform', "rotate("+second_deg+"deg)");

		if (!reset) {
			$('.second').addClass('ease');
		}
		
		reset = false;

	}, 1000);

});
```
变量 reset 的作用是当表盘初始化时，秒针不会疯狂转圈。
